### ISSUE TITLE
Remove source maps from inline CSS

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata-blocks#110]
While testing something unrelated I noticed this output for the Shopify block. We don't need this. Can webpack / wp-scripts be configured to produce a more simple file? Source maps are only a nice to have and we definitely don't need them in the inlined CSS.

<img width="1266" alt="Screenshot 2023-11-06 at 1 57 46 PM" src="https://github.com/thoughtis/cata-blocks/assets/226381/78b2f605-caf9-4715-9cf5-7d68872b8fa9">

**Comment by douglas-johnson** [comment]
@jessica-townsend Can you check what version of `@wordpress/scripts` is installed on your machine? I have `22.2.1` and I'm not able to build the Shopify block to address this issue.

The path to the file with the version number should be: `wp-content/plugins/cata-blocks/node_modules/@wordpress/scripts/package.json`

**Comment by jessica-townsend** [comment]
@douglas-johnson the version I have is `22.5.0`. It was updated last month in `cata-blocks/package.json` as part of https://github.com/thoughtis/cata-blocks/pull/103

**Comment by douglas-johnson** [comment]
Got it! thanks @jessica-townsend

**Comment by douglas-johnson** [comment]
@jessica-townsend I think this is a different in node environment. Mine is defaulting to production so when I run `npm run build` the source maps are omitted. But if I run `NODE_ENV=development npm run build` then the source maps are included.

I think my system is the one that is incorrect, but we still want the source maps to be omitted, so we'll have to update the build functions to use `NODE_ENV=production`
