### ISSUE TITLE
Add custom flex-grow control

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata-blocks#122]
The controls for the flex layout type allow, fit, fill and fixed sizes. We really need fixed and fill to work together. We run into multiple layouts that would benefit from support for uses cases like "20em by default and grow to fill the available space".

- Can we add control to the layout panel to set flex-grow as a number?
- Based on that, flex-grow be set in the style attribute of a block?

**Comment by jessica-townsend** [comment]
@douglas-johnson the solutions that I've seen for something like this involved adding a new control panel to certain blocks. Was there a different way to achieve this that you had in mind?

**Comment by douglas-johnson** [comment]
@jessica-townsend I think that sounds right, can you show me an example?

**Comment by jessica-townsend** [comment]
I have an unrefined solution for this here:
https://github.com/thoughtis/cata-blocks/blob/issue%23122/flex-grow-control/block-editor/src/index.js

This adds a Flex Grow attribute to all group blocks, but only displays an input field under `dimensions` if the block's parent has a `flex` layout and the block's width is set to `fixed`. An inline style gets added in the editor and on the frontend. Let me know what you think about this so far @douglas-johnson

**Comment by douglas-johnson** [comment]
@jessica-townsend I'm not able to see the control in the editor, what am I missing?

<img width="1294" alt="Screenshot 2024-02-01 at 1 58 29 PM" src="https://github.com/thoughtis/cata-blocks/assets/226381/b8a517db-f394-4209-beb6-1e4ed9da2238">

**Comment by jessica-townsend** [comment]
@douglas-johnson the control is currently only applied to group blocks, so the block structure should be like this
<img width="1155" alt="Screenshot 2024-02-01 at 11 02 47 AM" src="https://github.com/thoughtis/cata-blocks/assets/70295707/bc25dcb7-db11-47a9-af04-5bc42f40e098">

**Comment by douglas-johnson** [comment]
I set the flex-grow on these two headings in a Row, then I switched them to Fit instead of Fixed. I expected the flex-grow value to get reset to null, but it was still there in the output.

<img width="1052" alt="Screenshot 2024-02-08 at 12 37 50 PM" src="https://github.com/thoughtis/cata-blocks/assets/226381/ebe99577-1415-459f-b6db-e12fa7c1f1a4">

<img width="1157" alt="Screenshot 2024-02-08 at 12 37 13 PM" src="https://github.com/thoughtis/cata-blocks/assets/226381/a23de0e3-93d6-4d6f-8d69-861f321ad632">
