### ISSUE TITLE
Update Shop Catalog logo in Network Links block

### ISSUE THREAD

**Issue by jessica-townsend** [thoughtis/cata-blocks#143]
### Background
The logo for Shop Catalog has been slightly updated, and needs to be changed on the Network Links block.
[ShopCatalog_Logo_Horiz.svg.zip](https://github.com/thoughtis/cata-blocks/files/14951337/ShopCatalog_Logo_Horiz.svg.zip)

**Comment by douglas-johnson** [comment]
what is different about it?

**Comment by jessica-townsend** [comment]
It's very minor and isn't urgent, but the font is slightly different from the old logo. The new one is currently being used on the Shop Catalog site

Here's the old one:
<img width="756" alt="Screenshot 2024-04-12 at 6 59 28 AM" src="https://github.com/thoughtis/cata-blocks/assets/70295707/4d4ce8ae-7e9f-465f-adad-ab317532e596">

Here's the new one:
<img width="791" alt="Screenshot 2024-04-12 at 6 59 56 AM" src="https://github.com/thoughtis/cata-blocks/assets/70295707/c311f4c2-ca56-4275-9c30-c639a9156a16">

**Comment by jessica-townsend** [comment]
> What's the new font?

It matches the other typography on the site which is Plantin

**Comment by douglas-johnson** [comment]
Cool, we've switched back and forth between Minion Pro and Plantin before. No objections from me, just curious.
