### ISSUE TITLE
Products Block: save component and get_block_wrapper_attributes

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata-blocks#53]
### Background

In #50 we discussed using `get_block_wrapper_attributes()` in the product block's render_callback to get the HTML attributes including classnames. The `align*` classnames were missing on the first try, but I found that adding a save component to the block JavaScript made everything sync up and eliminated the need for use to customize the input to `get_block_wrapper_attributes` in PHP.

### Details

- See save component JSX below
- This is a breaking change, so this should be a minor version bump to `0.7.0`
- The editor will ask the user to attempt block recovery, which should work.
- Existing blocks will lose their `align*` classes so we'll need to edit, recover and save them after shipping this version.

#### Save Component
```jsx
/**
 * Products Block > Save
 */

/**
 * External dependencies
 */
 import { useBlockProps } from '@wordpress/block-editor';
 
/**
 * Save
 * 
 * @param {Object} props
 * @return {WPElement} Element to render.
 */
export default function save() {
	return (
		<div { ...useBlockProps.save() } />
	);
}
```

#### Using save component
For some reason ( distinction between component and function ? ) `Edit` is usually capitalized in WordPress's block examples, and `save` is usually all lowercase. I have kept up with this naming convention, but I'm not sure its important at all.
```js
import Edit from './edit';
import save from './save';
registerBlockType( 'cata/products', {
	edit: Edit,
        save
} );
```

**Comment by jessica-townsend** [comment]
Merged this update in PR #54
