### ISSUE TITLE
Scheduled content block

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata-blocks#85]
This would be a block with no intrinstic content. It would wrap any other set of blocks using InnerBlocks. It would have optional start and end datetime inputs. It could have four possible states:

- No start or end date
  - Content appears
- Start date, no end date
  - Content appears after the start date and doesn't stop
- Start date and end date
  - Content appears only between these dates
- No start date, end date
  - Content appears immediately, and stops at end date.

The responsibility to show or hide the content based on the date would be handled by a render_callback

**Comment by douglas-johnson** [comment]
### Adding controls for attributes using the InspectorControls slot fill.
https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/inspector-controls/README.md
https://developer.wordpress.org/block-editor/reference-guides/components/panel/
https://developer.wordpress.org/block-editor/reference-guides/components/date-time/

### Registering dynamic blocks
The WordPress docs for dynamic blocks, don't use block.json, which they should.
https://developer.wordpress.org/block-editor/how-to-guides/block-tutorial/creating-dynamic-blocks/
Using block.json makes it easy
https://github.com/thoughtis/cata-blocks/blob/0.7.12/blocks/products/products.php#L21-L26

### Using attributes and setAttributes with form controls

React components receive an object typically called `props` (that's why there are hooks like `useBlockProps` in the block editor).
https://react.dev/learn/passing-props-to-a-component

WordPress adds an `attributes` object and a `setAttributes` function to the props. You'll see this in lots of blocks:
`export default function Edit( {attributes, setAttributes}){`

Let's say you wanted to update the attribute `nickname` with a TextControl, you might set up the text control like this.

```jsx
<TextControl
  value={attributes.nickname}
  onChange={(nextNickname) => { setAttributes({nickname: nextNickname})}}
/>
```

Real example with text control:
https://github.com/thoughtis/cata-blocks/blob/0.7.12/blocks/products/src/edit.js#L134-L140

Example using a toggle control instead of text:
https://github.com/thoughtis/cata-blocks/blob/0.7.12/blocks/table-of-contents/src/edit.js

**Comment by jessica-townsend** [comment]
I have this functioning but there are a few kinks that need to be worked out:
- Need to fix time zone discrepancy, I assume the times should match Eastern time zone?
- Even if the date value is null, the picker shows the current date and time. I feel like this could be confusing for editors. Currently there's a reset link at the bottom of each date/time picker, but in the console I get a warning that it's deprecated and will be removed in a future version of the DateTimePicker component. Maybe having an "opt-in" checkbox for the start and end times would be a good idea and could help with both of these problems.
- Should we try to prevent someone from entering an end date that's before the start date?
- There's a style issue in each date/time picker. Not sure why
  <img width="282" alt="Screen Shot 2023-05-15 at 2 30 04 PM" src="https://github.com/thoughtis/cata-blocks/assets/70295707/db54944a-e835-40e1-9e0d-852620d3f1c0">

**Comment by douglas-johnson** [comment]
The timezone should match the site options. I know its possible to query server side, there might be an editor settings or options package that includes it for JS.

**Comment by douglas-johnson** [comment]
When the editor itself uses the date time picker, they're applying flex styling inline. I'm looking into how.

<img width="1284" alt="Screenshot 2023-05-16 at 10 59 07 AM" src="https://github.com/thoughtis/cata-blocks/assets/226381/94c863ed-8ef4-499d-8e72-65890444176d">

**Comment by douglas-johnson** [comment]
Our use of the date time picker is actually also getting that flex layout, its these two bits of margin breaking the flex layout.

<img width="517" alt="Screenshot 2023-05-16 at 11 18 11 AM" src="https://github.com/thoughtis/cata-blocks/assets/226381/64a4b5ce-9243-42cc-8145-6c322c20c73b">

**Comment by jessica-townsend** [comment]
Alright, in that case I'll just leave our CSS there to get rid of it
