### ISSUE TITLE
Substack logo

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata-blocks#93]
Can we add a Social Link variation for substack that includes their logo?

Guide to variations:
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-variations/

It looks like all the current social icons are variations:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/variations.js

Here's an svg version of their logo you can adapt to fit the SVG component used in the social links.
```svg
<svg width="24" height="24" viewBox="0 0 24 24" version="1.1">
	<path d="m22.54,5.41H1.46v2.84h21.08v-2.84Z"/>
	<path d="m1.46,10.81v13.19l10.54-5.89,10.54,5.89v-13.19H1.46Z"/>
	<path d="m22.54,0H1.46v2.84h21.08V0Z"/>
</svg>
```

Example SVG component icon
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/icons/facebook.js

**Comment by jessica-townsend** [comment]
@douglas-johnson I have this started locally and I'm able to select a block variation with the correct name and logo in the editor. However, the default icon displays on the frontend. It looks like the following functions control what icon gets displayed:
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/index.php#L47
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/index.php#L94
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/social-link/index.php#L127

What do you think would be the best method for the substack logo to be shown on the frontend?

**Comment by douglas-johnson** [comment]
What in the world? That suuuucks. They don't have a filter to add another service.

Seems like this PR to add one stalled out in the fall.

https://github.com/WordPress/gutenberg/pull/30749

Hold for now

**Comment by douglas-johnson** [comment]
https://github.com/WordPress/gutenberg/pull/30749#issuecomment-1621908230
